// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/property/v1/property.proto

package com.ecmsp.product.v1.property.v1;

public interface DeletePropertyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.property.v1.DeletePropertyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
