// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/property/v1/property.proto

package com.ecmsp.product.v1.property.v1;

public interface DeletePropertyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.property.v1.DeletePropertyResponse)
    com.google.protobuf.MessageOrBuilder {
}
