// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/variant/v1/variant.proto

package com.ecmsp.product.v1.variant.v1;

public interface CreateVariantRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.variant.v1.CreateVariantRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_id = 1;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 1;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>.google.type.Decimal price = 2;</code>
   * @return Whether the price field is set.
   */
  boolean hasPrice();
  /**
   * <code>.google.type.Decimal price = 2;</code>
   * @return The price.
   */
  com.google.type.Decimal getPrice();
  /**
   * <code>.google.type.Decimal price = 2;</code>
   */
  com.google.type.DecimalOrBuilder getPriceOrBuilder();

  /**
   * <code>int32 stock_quantity = 3;</code>
   * @return The stockQuantity.
   */
  int getStockQuantity();

  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated string variant_images = 5;</code>
   * @return A list containing the variantImages.
   */
  java.util.List<java.lang.String>
      getVariantImagesList();
  /**
   * <code>repeated string variant_images = 5;</code>
   * @return The count of variantImages.
   */
  int getVariantImagesCount();
  /**
   * <code>repeated string variant_images = 5;</code>
   * @param index The index of the element to return.
   * @return The variantImages at the given index.
   */
  java.lang.String getVariantImages(int index);
  /**
   * <code>repeated string variant_images = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the variantImages at the given index.
   */
  com.google.protobuf.ByteString
      getVariantImagesBytes(int index);

  /**
   * <code>repeated .product.v1.variant.v1.VariantPropertyValue variant_property_values = 6;</code>
   */
  java.util.List<com.ecmsp.product.v1.variant.v1.VariantPropertyValue> 
      getVariantPropertyValuesList();
  /**
   * <code>repeated .product.v1.variant.v1.VariantPropertyValue variant_property_values = 6;</code>
   */
  com.ecmsp.product.v1.variant.v1.VariantPropertyValue getVariantPropertyValues(int index);
  /**
   * <code>repeated .product.v1.variant.v1.VariantPropertyValue variant_property_values = 6;</code>
   */
  int getVariantPropertyValuesCount();
  /**
   * <code>repeated .product.v1.variant.v1.VariantPropertyValue variant_property_values = 6;</code>
   */
  java.util.List<? extends com.ecmsp.product.v1.variant.v1.VariantPropertyValueOrBuilder> 
      getVariantPropertyValuesOrBuilderList();
  /**
   * <code>repeated .product.v1.variant.v1.VariantPropertyValue variant_property_values = 6;</code>
   */
  com.ecmsp.product.v1.variant.v1.VariantPropertyValueOrBuilder getVariantPropertyValuesOrBuilder(
      int index);
}
