// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/variant/v1/variant_service.proto

package com.ecmsp.product.v1.variant.v1;

public final class VariantServiceProto {
  private VariantServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+product/v1/variant/v1/variant_service." +
      "proto\022\025product.v1.variant.v1\032#product/v1" +
      "/variant/v1/variant.proto2\354\001\n\016VariantSer" +
      "vice\022l\n\rCreateVariant\022+.product.v1.varia" +
      "nt.v1.CreateVariantRequest\032,.product.v1." +
      "variant.v1.CreateVariantResponse\"\000\022l\n\rDe" +
      "leteVariant\022+.product.v1.variant.v1.Dele" +
      "teVariantRequest\032,.product.v1.variant.v1" +
      ".DeleteVariantResponse\"\000B8\n\037com.ecmsp.pr" +
      "oduct.v1.variant.v1B\023VariantServiceProto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ecmsp.product.v1.variant.v1.VariantProto.getDescriptor(),
        });
    com.ecmsp.product.v1.variant.v1.VariantProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
