// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/category/v1/category_service.proto

package com.ecmsp.product.v1.category.v1;

public final class CategoryServiceProto {
  private CategoryServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-product/v1/category/v1/category_servic" +
      "e.proto\022\026product.v1.category.v1\032%product" +
      "/v1/category/v1/category.proto2\367\001\n\017Categ" +
      "oryService\022q\n\016CreateCategory\022-.product.v" +
      "1.category.v1.CreateCategoryRequest\032..pr" +
      "oduct.v1.category.v1.CreateCategoryRespo" +
      "nse\"\000\022q\n\016DeleteCategory\022-.product.v1.cat" +
      "egory.v1.DeleteCategoryRequest\032..product" +
      ".v1.category.v1.DeleteCategoryResponse\"\000" +
      "B:\n com.ecmsp.product.v1.category.v1B\024Ca" +
      "tegoryServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ecmsp.product.v1.category.v1.CategoryProto.getDescriptor(),
        });
    com.ecmsp.product.v1.category.v1.CategoryProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
