// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/delivery/v1/delivery.proto

package com.ecmsp.product.v1.delivery.v1;

public interface RecordDeliveryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.delivery.v1.RecordDeliveryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .product.v1.delivery.v1.DeliveryItem items = 1;</code>
   */
  java.util.List<com.ecmsp.product.v1.delivery.v1.DeliveryItem> 
      getItemsList();
  /**
   * <code>repeated .product.v1.delivery.v1.DeliveryItem items = 1;</code>
   */
  com.ecmsp.product.v1.delivery.v1.DeliveryItem getItems(int index);
  /**
   * <code>repeated .product.v1.delivery.v1.DeliveryItem items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .product.v1.delivery.v1.DeliveryItem items = 1;</code>
   */
  java.util.List<? extends com.ecmsp.product.v1.delivery.v1.DeliveryItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .product.v1.delivery.v1.DeliveryItem items = 1;</code>
   */
  com.ecmsp.product.v1.delivery.v1.DeliveryItemOrBuilder getItemsOrBuilder(
      int index);
}
