// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/v1/user_service.proto

package com.ecmsp.user.v1;

public interface ListAllPermissionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.v1.ListAllPermissionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string permissions = 1;</code>
   * @return A list containing the permissions.
   */
  java.util.List<java.lang.String>
      getPermissionsList();
  /**
   * <code>repeated string permissions = 1;</code>
   * @return The count of permissions.
   */
  int getPermissionsCount();
  /**
   * <code>repeated string permissions = 1;</code>
   * @param index The index of the element to return.
   * @return The permissions at the given index.
   */
  java.lang.String getPermissions(int index);
  /**
   * <code>repeated string permissions = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the permissions at the given index.
   */
  com.google.protobuf.ByteString
      getPermissionsBytes(int index);
}
