// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/reservation/v1/variant_reservation.proto

package com.ecmsp.product.v1.reservation.v1;

public interface RemoveVariantsReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.reservation.v1.RemoveVariantsReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
