// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/reservation/v1/variant_reservation.proto

package com.ecmsp.product.v1.reservation.v1;

public final class VariantReservationProto {
  private VariantReservationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_v1_reservation_v1_CreateVariantsReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_v1_reservation_v1_CreateVariantsReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_v1_reservation_v1_CreateVariantsReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_v1_reservation_v1_CreateVariantsReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_v1_reservation_v1_FailedReservationVariant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_v1_reservation_v1_FailedReservationVariant_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_v1_reservation_v1_RemoveVariantsReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_v1_reservation_v1_RemoveVariantsReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_v1_reservation_v1_RemoveVariantsReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_v1_reservation_v1_RemoveVariantsReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_v1_reservation_v1_GetVariantsReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_v1_reservation_v1_GetVariantsReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_v1_reservation_v1_GetVariantsReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_v1_reservation_v1_GetVariantsReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_v1_reservation_v1_ReservedVariant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_v1_reservation_v1_ReservedVariant_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3product/v1/reservation/v1/variant_rese" +
      "rvation.proto\022\031product.v1.reservation.v1" +
      "\"]\n CreateVariantsReservationRequest\0229\n\005" +
      "items\030\001 \003(\0132*.product.v1.reservation.v1." +
      "ReservedVariant\"\247\001\n!CreateVariantsReserv" +
      "ationResponse\022\026\n\016reservation_id\030\001 \001(\t\022\034\n" +
      "\024reserved_variant_ids\030\003 \003(\t\022L\n\017failed_va" +
      "riants\030\004 \003(\01323.product.v1.reservation.v1" +
      ".FailedReservationVariant\"f\n\030FailedReser" +
      "vationVariant\022\022\n\nvariant_id\030\001 \001(\t\022\032\n\022req" +
      "uested_quantity\030\002 \001(\005\022\032\n\022available_quant" +
      "ity\030\003 \001(\005\":\n RemoveVariantsReservationRe" +
      "quest\022\026\n\016reservation_id\030\001 \001(\t\"4\n!RemoveV" +
      "ariantsReservationResponse\022\017\n\007message\030\002 " +
      "\001(\t\"7\n\035GetVariantsReservationRequest\022\026\n\016" +
      "reservation_id\030\001 \001(\t\"[\n\036GetVariantsReser" +
      "vationResponse\0229\n\005items\030\001 \003(\0132*.product." +
      "v1.reservation.v1.ReservedVariant\"7\n\017Res" +
      "ervedVariant\022\022\n\nvariant_id\030\001 \001(\t\022\020\n\010quan" +
      "tity\030\002 \001(\005B@\n#com.ecmsp.product.v1.reser" +
      "vation.v1B\027VariantReservationProtoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_product_v1_reservation_v1_CreateVariantsReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_product_v1_reservation_v1_CreateVariantsReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_v1_reservation_v1_CreateVariantsReservationRequest_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_product_v1_reservation_v1_CreateVariantsReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_product_v1_reservation_v1_CreateVariantsReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_v1_reservation_v1_CreateVariantsReservationResponse_descriptor,
        new java.lang.String[] { "ReservationId", "ReservedVariantIds", "FailedVariants", });
    internal_static_product_v1_reservation_v1_FailedReservationVariant_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_product_v1_reservation_v1_FailedReservationVariant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_v1_reservation_v1_FailedReservationVariant_descriptor,
        new java.lang.String[] { "VariantId", "RequestedQuantity", "AvailableQuantity", });
    internal_static_product_v1_reservation_v1_RemoveVariantsReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_product_v1_reservation_v1_RemoveVariantsReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_v1_reservation_v1_RemoveVariantsReservationRequest_descriptor,
        new java.lang.String[] { "ReservationId", });
    internal_static_product_v1_reservation_v1_RemoveVariantsReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_product_v1_reservation_v1_RemoveVariantsReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_v1_reservation_v1_RemoveVariantsReservationResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_product_v1_reservation_v1_GetVariantsReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_product_v1_reservation_v1_GetVariantsReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_v1_reservation_v1_GetVariantsReservationRequest_descriptor,
        new java.lang.String[] { "ReservationId", });
    internal_static_product_v1_reservation_v1_GetVariantsReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_product_v1_reservation_v1_GetVariantsReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_v1_reservation_v1_GetVariantsReservationResponse_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_product_v1_reservation_v1_ReservedVariant_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_product_v1_reservation_v1_ReservedVariant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_v1_reservation_v1_ReservedVariant_descriptor,
        new java.lang.String[] { "VariantId", "Quantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
