// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/v1/cart.proto

package com.ecmsp.cart.v1;

public interface CartProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cart.v1.CartProduct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 cart_id = 1;</code>
   * @return The cartId.
   */
  int getCartId();

  /**
   * <code>string product_id = 2;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 2;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  int getQuantity();
}
