// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart/v1/cart_service.proto

package com.ecmsp.cart.v1;

/**
 * Protobuf type {@code cart.v1.DeleteProductFromCartRequest}
 */
public final class DeleteProductFromCartRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cart.v1.DeleteProductFromCartRequest)
    DeleteProductFromCartRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeleteProductFromCartRequest.newBuilder() to construct.
  private DeleteProductFromCartRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeleteProductFromCartRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeleteProductFromCartRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ecmsp.cart.v1.CartServiceProto.internal_static_cart_v1_DeleteProductFromCartRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ecmsp.cart.v1.CartServiceProto.internal_static_cart_v1_DeleteProductFromCartRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ecmsp.cart.v1.DeleteProductFromCartRequest.class, com.ecmsp.cart.v1.DeleteProductFromCartRequest.Builder.class);
  }

  public static final int DELETE_REQUEST_FIELD_NUMBER = 1;
  private com.ecmsp.cart.v1.DeleteProductRequest deleteRequest_;
  /**
   * <code>.cart.v1.DeleteProductRequest delete_request = 1;</code>
   * @return Whether the deleteRequest field is set.
   */
  @java.lang.Override
  public boolean hasDeleteRequest() {
    return deleteRequest_ != null;
  }
  /**
   * <code>.cart.v1.DeleteProductRequest delete_request = 1;</code>
   * @return The deleteRequest.
   */
  @java.lang.Override
  public com.ecmsp.cart.v1.DeleteProductRequest getDeleteRequest() {
    return deleteRequest_ == null ? com.ecmsp.cart.v1.DeleteProductRequest.getDefaultInstance() : deleteRequest_;
  }
  /**
   * <code>.cart.v1.DeleteProductRequest delete_request = 1;</code>
   */
  @java.lang.Override
  public com.ecmsp.cart.v1.DeleteProductRequestOrBuilder getDeleteRequestOrBuilder() {
    return deleteRequest_ == null ? com.ecmsp.cart.v1.DeleteProductRequest.getDefaultInstance() : deleteRequest_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (deleteRequest_ != null) {
      output.writeMessage(1, getDeleteRequest());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (deleteRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDeleteRequest());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ecmsp.cart.v1.DeleteProductFromCartRequest)) {
      return super.equals(obj);
    }
    com.ecmsp.cart.v1.DeleteProductFromCartRequest other = (com.ecmsp.cart.v1.DeleteProductFromCartRequest) obj;

    if (hasDeleteRequest() != other.hasDeleteRequest()) return false;
    if (hasDeleteRequest()) {
      if (!getDeleteRequest()
          .equals(other.getDeleteRequest())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDeleteRequest()) {
      hash = (37 * hash) + DELETE_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getDeleteRequest().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ecmsp.cart.v1.DeleteProductFromCartRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecmsp.cart.v1.DeleteProductFromCartRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecmsp.cart.v1.DeleteProductFromCartRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecmsp.cart.v1.DeleteProductFromCartRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecmsp.cart.v1.DeleteProductFromCartRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecmsp.cart.v1.DeleteProductFromCartRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecmsp.cart.v1.DeleteProductFromCartRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecmsp.cart.v1.DeleteProductFromCartRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ecmsp.cart.v1.DeleteProductFromCartRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ecmsp.cart.v1.DeleteProductFromCartRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ecmsp.cart.v1.DeleteProductFromCartRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecmsp.cart.v1.DeleteProductFromCartRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ecmsp.cart.v1.DeleteProductFromCartRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cart.v1.DeleteProductFromCartRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cart.v1.DeleteProductFromCartRequest)
      com.ecmsp.cart.v1.DeleteProductFromCartRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ecmsp.cart.v1.CartServiceProto.internal_static_cart_v1_DeleteProductFromCartRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ecmsp.cart.v1.CartServiceProto.internal_static_cart_v1_DeleteProductFromCartRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ecmsp.cart.v1.DeleteProductFromCartRequest.class, com.ecmsp.cart.v1.DeleteProductFromCartRequest.Builder.class);
    }

    // Construct using com.ecmsp.cart.v1.DeleteProductFromCartRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      deleteRequest_ = null;
      if (deleteRequestBuilder_ != null) {
        deleteRequestBuilder_.dispose();
        deleteRequestBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ecmsp.cart.v1.CartServiceProto.internal_static_cart_v1_DeleteProductFromCartRequest_descriptor;
    }

    @java.lang.Override
    public com.ecmsp.cart.v1.DeleteProductFromCartRequest getDefaultInstanceForType() {
      return com.ecmsp.cart.v1.DeleteProductFromCartRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ecmsp.cart.v1.DeleteProductFromCartRequest build() {
      com.ecmsp.cart.v1.DeleteProductFromCartRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ecmsp.cart.v1.DeleteProductFromCartRequest buildPartial() {
      com.ecmsp.cart.v1.DeleteProductFromCartRequest result = new com.ecmsp.cart.v1.DeleteProductFromCartRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ecmsp.cart.v1.DeleteProductFromCartRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.deleteRequest_ = deleteRequestBuilder_ == null
            ? deleteRequest_
            : deleteRequestBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ecmsp.cart.v1.DeleteProductFromCartRequest) {
        return mergeFrom((com.ecmsp.cart.v1.DeleteProductFromCartRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ecmsp.cart.v1.DeleteProductFromCartRequest other) {
      if (other == com.ecmsp.cart.v1.DeleteProductFromCartRequest.getDefaultInstance()) return this;
      if (other.hasDeleteRequest()) {
        mergeDeleteRequest(other.getDeleteRequest());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getDeleteRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.ecmsp.cart.v1.DeleteProductRequest deleteRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecmsp.cart.v1.DeleteProductRequest, com.ecmsp.cart.v1.DeleteProductRequest.Builder, com.ecmsp.cart.v1.DeleteProductRequestOrBuilder> deleteRequestBuilder_;
    /**
     * <code>.cart.v1.DeleteProductRequest delete_request = 1;</code>
     * @return Whether the deleteRequest field is set.
     */
    public boolean hasDeleteRequest() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.cart.v1.DeleteProductRequest delete_request = 1;</code>
     * @return The deleteRequest.
     */
    public com.ecmsp.cart.v1.DeleteProductRequest getDeleteRequest() {
      if (deleteRequestBuilder_ == null) {
        return deleteRequest_ == null ? com.ecmsp.cart.v1.DeleteProductRequest.getDefaultInstance() : deleteRequest_;
      } else {
        return deleteRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.cart.v1.DeleteProductRequest delete_request = 1;</code>
     */
    public Builder setDeleteRequest(com.ecmsp.cart.v1.DeleteProductRequest value) {
      if (deleteRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deleteRequest_ = value;
      } else {
        deleteRequestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.cart.v1.DeleteProductRequest delete_request = 1;</code>
     */
    public Builder setDeleteRequest(
        com.ecmsp.cart.v1.DeleteProductRequest.Builder builderForValue) {
      if (deleteRequestBuilder_ == null) {
        deleteRequest_ = builderForValue.build();
      } else {
        deleteRequestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.cart.v1.DeleteProductRequest delete_request = 1;</code>
     */
    public Builder mergeDeleteRequest(com.ecmsp.cart.v1.DeleteProductRequest value) {
      if (deleteRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          deleteRequest_ != null &&
          deleteRequest_ != com.ecmsp.cart.v1.DeleteProductRequest.getDefaultInstance()) {
          getDeleteRequestBuilder().mergeFrom(value);
        } else {
          deleteRequest_ = value;
        }
      } else {
        deleteRequestBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.cart.v1.DeleteProductRequest delete_request = 1;</code>
     */
    public Builder clearDeleteRequest() {
      bitField0_ = (bitField0_ & ~0x00000001);
      deleteRequest_ = null;
      if (deleteRequestBuilder_ != null) {
        deleteRequestBuilder_.dispose();
        deleteRequestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.cart.v1.DeleteProductRequest delete_request = 1;</code>
     */
    public com.ecmsp.cart.v1.DeleteProductRequest.Builder getDeleteRequestBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDeleteRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.cart.v1.DeleteProductRequest delete_request = 1;</code>
     */
    public com.ecmsp.cart.v1.DeleteProductRequestOrBuilder getDeleteRequestOrBuilder() {
      if (deleteRequestBuilder_ != null) {
        return deleteRequestBuilder_.getMessageOrBuilder();
      } else {
        return deleteRequest_ == null ?
            com.ecmsp.cart.v1.DeleteProductRequest.getDefaultInstance() : deleteRequest_;
      }
    }
    /**
     * <code>.cart.v1.DeleteProductRequest delete_request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecmsp.cart.v1.DeleteProductRequest, com.ecmsp.cart.v1.DeleteProductRequest.Builder, com.ecmsp.cart.v1.DeleteProductRequestOrBuilder> 
        getDeleteRequestFieldBuilder() {
      if (deleteRequestBuilder_ == null) {
        deleteRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ecmsp.cart.v1.DeleteProductRequest, com.ecmsp.cart.v1.DeleteProductRequest.Builder, com.ecmsp.cart.v1.DeleteProductRequestOrBuilder>(
                getDeleteRequest(),
                getParentForChildren(),
                isClean());
        deleteRequest_ = null;
      }
      return deleteRequestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cart.v1.DeleteProductFromCartRequest)
  }

  // @@protoc_insertion_point(class_scope:cart.v1.DeleteProductFromCartRequest)
  private static final com.ecmsp.cart.v1.DeleteProductFromCartRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ecmsp.cart.v1.DeleteProductFromCartRequest();
  }

  public static com.ecmsp.cart.v1.DeleteProductFromCartRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeleteProductFromCartRequest>
      PARSER = new com.google.protobuf.AbstractParser<DeleteProductFromCartRequest>() {
    @java.lang.Override
    public DeleteProductFromCartRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeleteProductFromCartRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeleteProductFromCartRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ecmsp.cart.v1.DeleteProductFromCartRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

