// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/v1/returns/v1/return_service.proto

package com.ecmsp.order.v1.returns.v1;

public interface CreateReturnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.v1.returns.v1.CreateReturnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order_id = 1;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 1;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>repeated .order.v1.returns.v1.ReturnItemReason items = 2;</code>
   */
  java.util.List<com.ecmsp.order.v1.returns.v1.ReturnItemReason> 
      getItemsList();
  /**
   * <code>repeated .order.v1.returns.v1.ReturnItemReason items = 2;</code>
   */
  com.ecmsp.order.v1.returns.v1.ReturnItemReason getItems(int index);
  /**
   * <code>repeated .order.v1.returns.v1.ReturnItemReason items = 2;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .order.v1.returns.v1.ReturnItemReason items = 2;</code>
   */
  java.util.List<? extends com.ecmsp.order.v1.returns.v1.ReturnItemReasonOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .order.v1.returns.v1.ReturnItemReason items = 2;</code>
   */
  com.ecmsp.order.v1.returns.v1.ReturnItemReasonOrBuilder getItemsOrBuilder(
      int index);
}
