// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/v1/returns/v1/return_service.proto

package com.ecmsp.order.v1.returns.v1;

public interface ListReturnsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.v1.returns.v1.ListReturnsRequest)
    com.google.protobuf.MessageOrBuilder {
}
