// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/v1/returns/v1/return_service.proto

package com.ecmsp.order.v1.returns.v1;

public interface ListReturnsByUserIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.v1.returns.v1.ListReturnsByUserIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .order.v1.returns.v1.Return returns = 1;</code>
   */
  java.util.List<com.ecmsp.order.v1.returns.v1.Return> 
      getReturnsList();
  /**
   * <code>repeated .order.v1.returns.v1.Return returns = 1;</code>
   */
  com.ecmsp.order.v1.returns.v1.Return getReturns(int index);
  /**
   * <code>repeated .order.v1.returns.v1.Return returns = 1;</code>
   */
  int getReturnsCount();
  /**
   * <code>repeated .order.v1.returns.v1.Return returns = 1;</code>
   */
  java.util.List<? extends com.ecmsp.order.v1.returns.v1.ReturnOrBuilder> 
      getReturnsOrBuilderList();
  /**
   * <code>repeated .order.v1.returns.v1.Return returns = 1;</code>
   */
  com.ecmsp.order.v1.returns.v1.ReturnOrBuilder getReturnsOrBuilder(
      int index);
}
