// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/v1/returns/v1/return_status.proto

package com.ecmsp.order.v1.returns.v1;

public final class ReturnStatusProto {
  private ReturnStatusProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'order/v1/returns/v1/return_status.prot" +
      "o\022\023order.v1.returns.v1*\205\001\n\014ReturnStatus\022" +
      "\035\n\031RETURN_STATUS_UNSPECIFIED\020\000\022\033\n\027RETURN" +
      "_STATUS_REQUESTED\020\001\022\034\n\030RETURN_STATUS_PRO" +
      "CESSING\020\002\022\033\n\027RETURN_STATUS_COMPLETED\020\003B4" +
      "\n\035com.ecmsp.order.v1.returns.v1B\021ReturnS" +
      "tatusProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
