// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/v1/returns/v1/return.proto

package com.ecmsp.order.v1.returns.v1;

public interface ReturnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.v1.returns.v1.Return)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string return_id = 1;</code>
   * @return The returnId.
   */
  java.lang.String getReturnId();
  /**
   * <code>string return_id = 1;</code>
   * @return The bytes for returnId.
   */
  com.google.protobuf.ByteString
      getReturnIdBytes();

  /**
   * <code>string order_id = 2;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 2;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>repeated string item_ids = 3;</code>
   * @return A list containing the itemIds.
   */
  java.util.List<java.lang.String>
      getItemIdsList();
  /**
   * <code>repeated string item_ids = 3;</code>
   * @return The count of itemIds.
   */
  int getItemIdsCount();
  /**
   * <code>repeated string item_ids = 3;</code>
   * @param index The index of the element to return.
   * @return The itemIds at the given index.
   */
  java.lang.String getItemIds(int index);
  /**
   * <code>repeated string item_ids = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the itemIds at the given index.
   */
  com.google.protobuf.ByteString
      getItemIdsBytes(int index);

  /**
   * <code>.order.v1.returns.v1.ReturnStatus status = 4;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.order.v1.returns.v1.ReturnStatus status = 4;</code>
   * @return The status.
   */
  com.ecmsp.order.v1.returns.v1.ReturnStatus getStatus();

  /**
   * <code>string created_at = 5;</code>
   * @return The createdAt.
   */
  java.lang.String getCreatedAt();
  /**
   * <code>string created_at = 5;</code>
   * @return The bytes for createdAt.
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();
}
