// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/variant_reservation.proto

package com.ecmsp.product.v1;

/**
 * Protobuf type {@code product.v1.CreateVariantsReservationResponse}
 */
public final class CreateVariantsReservationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:product.v1.CreateVariantsReservationResponse)
    CreateVariantsReservationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateVariantsReservationResponse.newBuilder() to construct.
  private CreateVariantsReservationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateVariantsReservationResponse() {
    reservationId_ = "";
    reservedVariantIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    failedVariants_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateVariantsReservationResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ecmsp.product.v1.VariantReservationProto.internal_static_product_v1_CreateVariantsReservationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ecmsp.product.v1.VariantReservationProto.internal_static_product_v1_CreateVariantsReservationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ecmsp.product.v1.CreateVariantsReservationResponse.class, com.ecmsp.product.v1.CreateVariantsReservationResponse.Builder.class);
  }

  public static final int RESERVATION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reservationId_ = "";
  /**
   * <code>string reservation_id = 1;</code>
   * @return The reservationId.
   */
  @java.lang.Override
  public java.lang.String getReservationId() {
    java.lang.Object ref = reservationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reservationId_ = s;
      return s;
    }
  }
  /**
   * <code>string reservation_id = 1;</code>
   * @return The bytes for reservationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReservationIdBytes() {
    java.lang.Object ref = reservationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reservationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESERVED_VARIANT_IDS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList reservedVariantIds_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string reserved_variant_ids = 3;</code>
   * @return A list containing the reservedVariantIds.
   */
  public com.google.protobuf.ProtocolStringList
      getReservedVariantIdsList() {
    return reservedVariantIds_;
  }
  /**
   * <code>repeated string reserved_variant_ids = 3;</code>
   * @return The count of reservedVariantIds.
   */
  public int getReservedVariantIdsCount() {
    return reservedVariantIds_.size();
  }
  /**
   * <code>repeated string reserved_variant_ids = 3;</code>
   * @param index The index of the element to return.
   * @return The reservedVariantIds at the given index.
   */
  public java.lang.String getReservedVariantIds(int index) {
    return reservedVariantIds_.get(index);
  }
  /**
   * <code>repeated string reserved_variant_ids = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the reservedVariantIds at the given index.
   */
  public com.google.protobuf.ByteString
      getReservedVariantIdsBytes(int index) {
    return reservedVariantIds_.getByteString(index);
  }

  public static final int FAILED_VARIANTS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.ecmsp.product.v1.FailedReservationVariant> failedVariants_;
  /**
   * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.ecmsp.product.v1.FailedReservationVariant> getFailedVariantsList() {
    return failedVariants_;
  }
  /**
   * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ecmsp.product.v1.FailedReservationVariantOrBuilder> 
      getFailedVariantsOrBuilderList() {
    return failedVariants_;
  }
  /**
   * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
   */
  @java.lang.Override
  public int getFailedVariantsCount() {
    return failedVariants_.size();
  }
  /**
   * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
   */
  @java.lang.Override
  public com.ecmsp.product.v1.FailedReservationVariant getFailedVariants(int index) {
    return failedVariants_.get(index);
  }
  /**
   * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
   */
  @java.lang.Override
  public com.ecmsp.product.v1.FailedReservationVariantOrBuilder getFailedVariantsOrBuilder(
      int index) {
    return failedVariants_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reservationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reservationId_);
    }
    for (int i = 0; i < reservedVariantIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reservedVariantIds_.getRaw(i));
    }
    for (int i = 0; i < failedVariants_.size(); i++) {
      output.writeMessage(4, failedVariants_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reservationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reservationId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < reservedVariantIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(reservedVariantIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getReservedVariantIdsList().size();
    }
    for (int i = 0; i < failedVariants_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, failedVariants_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ecmsp.product.v1.CreateVariantsReservationResponse)) {
      return super.equals(obj);
    }
    com.ecmsp.product.v1.CreateVariantsReservationResponse other = (com.ecmsp.product.v1.CreateVariantsReservationResponse) obj;

    if (!getReservationId()
        .equals(other.getReservationId())) return false;
    if (!getReservedVariantIdsList()
        .equals(other.getReservedVariantIdsList())) return false;
    if (!getFailedVariantsList()
        .equals(other.getFailedVariantsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESERVATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReservationId().hashCode();
    if (getReservedVariantIdsCount() > 0) {
      hash = (37 * hash) + RESERVED_VARIANT_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getReservedVariantIdsList().hashCode();
    }
    if (getFailedVariantsCount() > 0) {
      hash = (37 * hash) + FAILED_VARIANTS_FIELD_NUMBER;
      hash = (53 * hash) + getFailedVariantsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ecmsp.product.v1.CreateVariantsReservationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecmsp.product.v1.CreateVariantsReservationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecmsp.product.v1.CreateVariantsReservationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecmsp.product.v1.CreateVariantsReservationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecmsp.product.v1.CreateVariantsReservationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecmsp.product.v1.CreateVariantsReservationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecmsp.product.v1.CreateVariantsReservationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecmsp.product.v1.CreateVariantsReservationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ecmsp.product.v1.CreateVariantsReservationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ecmsp.product.v1.CreateVariantsReservationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ecmsp.product.v1.CreateVariantsReservationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecmsp.product.v1.CreateVariantsReservationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ecmsp.product.v1.CreateVariantsReservationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code product.v1.CreateVariantsReservationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:product.v1.CreateVariantsReservationResponse)
      com.ecmsp.product.v1.CreateVariantsReservationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ecmsp.product.v1.VariantReservationProto.internal_static_product_v1_CreateVariantsReservationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ecmsp.product.v1.VariantReservationProto.internal_static_product_v1_CreateVariantsReservationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ecmsp.product.v1.CreateVariantsReservationResponse.class, com.ecmsp.product.v1.CreateVariantsReservationResponse.Builder.class);
    }

    // Construct using com.ecmsp.product.v1.CreateVariantsReservationResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      reservationId_ = "";
      reservedVariantIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (failedVariantsBuilder_ == null) {
        failedVariants_ = java.util.Collections.emptyList();
      } else {
        failedVariants_ = null;
        failedVariantsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ecmsp.product.v1.VariantReservationProto.internal_static_product_v1_CreateVariantsReservationResponse_descriptor;
    }

    @java.lang.Override
    public com.ecmsp.product.v1.CreateVariantsReservationResponse getDefaultInstanceForType() {
      return com.ecmsp.product.v1.CreateVariantsReservationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.ecmsp.product.v1.CreateVariantsReservationResponse build() {
      com.ecmsp.product.v1.CreateVariantsReservationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ecmsp.product.v1.CreateVariantsReservationResponse buildPartial() {
      com.ecmsp.product.v1.CreateVariantsReservationResponse result = new com.ecmsp.product.v1.CreateVariantsReservationResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.ecmsp.product.v1.CreateVariantsReservationResponse result) {
      if (failedVariantsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          failedVariants_ = java.util.Collections.unmodifiableList(failedVariants_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.failedVariants_ = failedVariants_;
      } else {
        result.failedVariants_ = failedVariantsBuilder_.build();
      }
    }

    private void buildPartial0(com.ecmsp.product.v1.CreateVariantsReservationResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.reservationId_ = reservationId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        reservedVariantIds_.makeImmutable();
        result.reservedVariantIds_ = reservedVariantIds_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ecmsp.product.v1.CreateVariantsReservationResponse) {
        return mergeFrom((com.ecmsp.product.v1.CreateVariantsReservationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ecmsp.product.v1.CreateVariantsReservationResponse other) {
      if (other == com.ecmsp.product.v1.CreateVariantsReservationResponse.getDefaultInstance()) return this;
      if (!other.getReservationId().isEmpty()) {
        reservationId_ = other.reservationId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.reservedVariantIds_.isEmpty()) {
        if (reservedVariantIds_.isEmpty()) {
          reservedVariantIds_ = other.reservedVariantIds_;
          bitField0_ |= 0x00000002;
        } else {
          ensureReservedVariantIdsIsMutable();
          reservedVariantIds_.addAll(other.reservedVariantIds_);
        }
        onChanged();
      }
      if (failedVariantsBuilder_ == null) {
        if (!other.failedVariants_.isEmpty()) {
          if (failedVariants_.isEmpty()) {
            failedVariants_ = other.failedVariants_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFailedVariantsIsMutable();
            failedVariants_.addAll(other.failedVariants_);
          }
          onChanged();
        }
      } else {
        if (!other.failedVariants_.isEmpty()) {
          if (failedVariantsBuilder_.isEmpty()) {
            failedVariantsBuilder_.dispose();
            failedVariantsBuilder_ = null;
            failedVariants_ = other.failedVariants_;
            bitField0_ = (bitField0_ & ~0x00000004);
            failedVariantsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFailedVariantsFieldBuilder() : null;
          } else {
            failedVariantsBuilder_.addAllMessages(other.failedVariants_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              reservationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureReservedVariantIdsIsMutable();
              reservedVariantIds_.add(s);
              break;
            } // case 26
            case 34: {
              com.ecmsp.product.v1.FailedReservationVariant m =
                  input.readMessage(
                      com.ecmsp.product.v1.FailedReservationVariant.parser(),
                      extensionRegistry);
              if (failedVariantsBuilder_ == null) {
                ensureFailedVariantsIsMutable();
                failedVariants_.add(m);
              } else {
                failedVariantsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object reservationId_ = "";
    /**
     * <code>string reservation_id = 1;</code>
     * @return The reservationId.
     */
    public java.lang.String getReservationId() {
      java.lang.Object ref = reservationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reservationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reservation_id = 1;</code>
     * @return The bytes for reservationId.
     */
    public com.google.protobuf.ByteString
        getReservationIdBytes() {
      java.lang.Object ref = reservationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reservationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reservation_id = 1;</code>
     * @param value The reservationId to set.
     * @return This builder for chaining.
     */
    public Builder setReservationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reservationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string reservation_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReservationId() {
      reservationId_ = getDefaultInstance().getReservationId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string reservation_id = 1;</code>
     * @param value The bytes for reservationId to set.
     * @return This builder for chaining.
     */
    public Builder setReservationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reservationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList reservedVariantIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureReservedVariantIdsIsMutable() {
      if (!reservedVariantIds_.isModifiable()) {
        reservedVariantIds_ = new com.google.protobuf.LazyStringArrayList(reservedVariantIds_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @return A list containing the reservedVariantIds.
     */
    public com.google.protobuf.ProtocolStringList
        getReservedVariantIdsList() {
      reservedVariantIds_.makeImmutable();
      return reservedVariantIds_;
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @return The count of reservedVariantIds.
     */
    public int getReservedVariantIdsCount() {
      return reservedVariantIds_.size();
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @param index The index of the element to return.
     * @return The reservedVariantIds at the given index.
     */
    public java.lang.String getReservedVariantIds(int index) {
      return reservedVariantIds_.get(index);
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the reservedVariantIds at the given index.
     */
    public com.google.protobuf.ByteString
        getReservedVariantIdsBytes(int index) {
      return reservedVariantIds_.getByteString(index);
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @param index The index to set the value at.
     * @param value The reservedVariantIds to set.
     * @return This builder for chaining.
     */
    public Builder setReservedVariantIds(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureReservedVariantIdsIsMutable();
      reservedVariantIds_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @param value The reservedVariantIds to add.
     * @return This builder for chaining.
     */
    public Builder addReservedVariantIds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureReservedVariantIdsIsMutable();
      reservedVariantIds_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @param values The reservedVariantIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllReservedVariantIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureReservedVariantIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, reservedVariantIds_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReservedVariantIds() {
      reservedVariantIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @param value The bytes of the reservedVariantIds to add.
     * @return This builder for chaining.
     */
    public Builder addReservedVariantIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureReservedVariantIdsIsMutable();
      reservedVariantIds_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<com.ecmsp.product.v1.FailedReservationVariant> failedVariants_ =
      java.util.Collections.emptyList();
    private void ensureFailedVariantsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        failedVariants_ = new java.util.ArrayList<com.ecmsp.product.v1.FailedReservationVariant>(failedVariants_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ecmsp.product.v1.FailedReservationVariant, com.ecmsp.product.v1.FailedReservationVariant.Builder, com.ecmsp.product.v1.FailedReservationVariantOrBuilder> failedVariantsBuilder_;

    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public java.util.List<com.ecmsp.product.v1.FailedReservationVariant> getFailedVariantsList() {
      if (failedVariantsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(failedVariants_);
      } else {
        return failedVariantsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public int getFailedVariantsCount() {
      if (failedVariantsBuilder_ == null) {
        return failedVariants_.size();
      } else {
        return failedVariantsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public com.ecmsp.product.v1.FailedReservationVariant getFailedVariants(int index) {
      if (failedVariantsBuilder_ == null) {
        return failedVariants_.get(index);
      } else {
        return failedVariantsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public Builder setFailedVariants(
        int index, com.ecmsp.product.v1.FailedReservationVariant value) {
      if (failedVariantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFailedVariantsIsMutable();
        failedVariants_.set(index, value);
        onChanged();
      } else {
        failedVariantsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public Builder setFailedVariants(
        int index, com.ecmsp.product.v1.FailedReservationVariant.Builder builderForValue) {
      if (failedVariantsBuilder_ == null) {
        ensureFailedVariantsIsMutable();
        failedVariants_.set(index, builderForValue.build());
        onChanged();
      } else {
        failedVariantsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public Builder addFailedVariants(com.ecmsp.product.v1.FailedReservationVariant value) {
      if (failedVariantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFailedVariantsIsMutable();
        failedVariants_.add(value);
        onChanged();
      } else {
        failedVariantsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public Builder addFailedVariants(
        int index, com.ecmsp.product.v1.FailedReservationVariant value) {
      if (failedVariantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFailedVariantsIsMutable();
        failedVariants_.add(index, value);
        onChanged();
      } else {
        failedVariantsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public Builder addFailedVariants(
        com.ecmsp.product.v1.FailedReservationVariant.Builder builderForValue) {
      if (failedVariantsBuilder_ == null) {
        ensureFailedVariantsIsMutable();
        failedVariants_.add(builderForValue.build());
        onChanged();
      } else {
        failedVariantsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public Builder addFailedVariants(
        int index, com.ecmsp.product.v1.FailedReservationVariant.Builder builderForValue) {
      if (failedVariantsBuilder_ == null) {
        ensureFailedVariantsIsMutable();
        failedVariants_.add(index, builderForValue.build());
        onChanged();
      } else {
        failedVariantsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public Builder addAllFailedVariants(
        java.lang.Iterable<? extends com.ecmsp.product.v1.FailedReservationVariant> values) {
      if (failedVariantsBuilder_ == null) {
        ensureFailedVariantsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, failedVariants_);
        onChanged();
      } else {
        failedVariantsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public Builder clearFailedVariants() {
      if (failedVariantsBuilder_ == null) {
        failedVariants_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        failedVariantsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public Builder removeFailedVariants(int index) {
      if (failedVariantsBuilder_ == null) {
        ensureFailedVariantsIsMutable();
        failedVariants_.remove(index);
        onChanged();
      } else {
        failedVariantsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public com.ecmsp.product.v1.FailedReservationVariant.Builder getFailedVariantsBuilder(
        int index) {
      return getFailedVariantsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public com.ecmsp.product.v1.FailedReservationVariantOrBuilder getFailedVariantsOrBuilder(
        int index) {
      if (failedVariantsBuilder_ == null) {
        return failedVariants_.get(index);  } else {
        return failedVariantsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public java.util.List<? extends com.ecmsp.product.v1.FailedReservationVariantOrBuilder> 
         getFailedVariantsOrBuilderList() {
      if (failedVariantsBuilder_ != null) {
        return failedVariantsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(failedVariants_);
      }
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public com.ecmsp.product.v1.FailedReservationVariant.Builder addFailedVariantsBuilder() {
      return getFailedVariantsFieldBuilder().addBuilder(
          com.ecmsp.product.v1.FailedReservationVariant.getDefaultInstance());
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public com.ecmsp.product.v1.FailedReservationVariant.Builder addFailedVariantsBuilder(
        int index) {
      return getFailedVariantsFieldBuilder().addBuilder(
          index, com.ecmsp.product.v1.FailedReservationVariant.getDefaultInstance());
    }
    /**
     * <code>repeated .product.v1.FailedReservationVariant failed_variants = 4;</code>
     */
    public java.util.List<com.ecmsp.product.v1.FailedReservationVariant.Builder> 
         getFailedVariantsBuilderList() {
      return getFailedVariantsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ecmsp.product.v1.FailedReservationVariant, com.ecmsp.product.v1.FailedReservationVariant.Builder, com.ecmsp.product.v1.FailedReservationVariantOrBuilder> 
        getFailedVariantsFieldBuilder() {
      if (failedVariantsBuilder_ == null) {
        failedVariantsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ecmsp.product.v1.FailedReservationVariant, com.ecmsp.product.v1.FailedReservationVariant.Builder, com.ecmsp.product.v1.FailedReservationVariantOrBuilder>(
                failedVariants_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        failedVariants_ = null;
      }
      return failedVariantsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:product.v1.CreateVariantsReservationResponse)
  }

  // @@protoc_insertion_point(class_scope:product.v1.CreateVariantsReservationResponse)
  private static final com.ecmsp.product.v1.CreateVariantsReservationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ecmsp.product.v1.CreateVariantsReservationResponse();
  }

  public static com.ecmsp.product.v1.CreateVariantsReservationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateVariantsReservationResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateVariantsReservationResponse>() {
    @java.lang.Override
    public CreateVariantsReservationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateVariantsReservationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateVariantsReservationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ecmsp.product.v1.CreateVariantsReservationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

