// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/product.proto

package com.ecmsp.product.v1;

public interface DeleteProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.DeleteProductResponse)
    com.google.protobuf.MessageOrBuilder {
}
