// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/product.proto

package com.ecmsp.product.v1;

public interface GetVariantsDetailsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.GetVariantsDetailsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_id = 1;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 1;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();
}
