// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/product_service.proto

package com.ecmsp.product.v1;

public final class ProductServiceProto {
  private ProductServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n product/v1/product_service.proto\022\nprod" +
      "uct.v1\032\030product/v1/product.proto2\252\002\n\016Pro" +
      "ductService\022N\n\013GetProducts\022\036.product.v1." +
      "GetProductsRequest\032\037.product.v1.GetProdu" +
      "ctsResponse\022c\n\022GetProductsByQuery\022%.prod" +
      "uct.v1.GetProductsByQueryRequest\032&.produ" +
      "ct.v1.GetProductsByQueryResponse\022c\n\022GetV" +
      "ariantsDetails\022%.product.v1.GetVariantsD" +
      "etailsRequest\032&.product.v1.GetVariantsDe" +
      "tailsResponseB-\n\024com.ecmsp.product.v1B\023P" +
      "roductServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ecmsp.product.v1.ProductProto.getDescriptor(),
        });
    com.ecmsp.product.v1.ProductProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
