// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/product_reservation_service.proto

package com.ecmsp.product.v1;

public interface ReleaseReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.ReleaseReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
