// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/product_reservation_service.proto

package com.ecmsp.product.v1;

/**
 * Protobuf type {@code product.v1.ReserveProductsResponse}
 */
public final class ReserveProductsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:product.v1.ReserveProductsResponse)
    ReserveProductsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReserveProductsResponse.newBuilder() to construct.
  private ReserveProductsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReserveProductsResponse() {
    message_ = "";
    reservedVariantIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    failedReservations_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReserveProductsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ecmsp.product.v1.ProductReservationServiceProto.internal_static_product_v1_ReserveProductsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ecmsp.product.v1.ProductReservationServiceProto.internal_static_product_v1_ReserveProductsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ecmsp.product.v1.ReserveProductsResponse.class, com.ecmsp.product.v1.ReserveProductsResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_ = false;
  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESERVED_VARIANT_IDS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList reservedVariantIds_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string reserved_variant_ids = 3;</code>
   * @return A list containing the reservedVariantIds.
   */
  public com.google.protobuf.ProtocolStringList
      getReservedVariantIdsList() {
    return reservedVariantIds_;
  }
  /**
   * <code>repeated string reserved_variant_ids = 3;</code>
   * @return The count of reservedVariantIds.
   */
  public int getReservedVariantIdsCount() {
    return reservedVariantIds_.size();
  }
  /**
   * <code>repeated string reserved_variant_ids = 3;</code>
   * @param index The index of the element to return.
   * @return The reservedVariantIds at the given index.
   */
  public java.lang.String getReservedVariantIds(int index) {
    return reservedVariantIds_.get(index);
  }
  /**
   * <code>repeated string reserved_variant_ids = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the reservedVariantIds at the given index.
   */
  public com.google.protobuf.ByteString
      getReservedVariantIdsBytes(int index) {
    return reservedVariantIds_.getByteString(index);
  }

  public static final int FAILED_RESERVATIONS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.ecmsp.product.v1.FailedReservation> failedReservations_;
  /**
   * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.ecmsp.product.v1.FailedReservation> getFailedReservationsList() {
    return failedReservations_;
  }
  /**
   * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ecmsp.product.v1.FailedReservationOrBuilder> 
      getFailedReservationsOrBuilderList() {
    return failedReservations_;
  }
  /**
   * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
   */
  @java.lang.Override
  public int getFailedReservationsCount() {
    return failedReservations_.size();
  }
  /**
   * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
   */
  @java.lang.Override
  public com.ecmsp.product.v1.FailedReservation getFailedReservations(int index) {
    return failedReservations_.get(index);
  }
  /**
   * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
   */
  @java.lang.Override
  public com.ecmsp.product.v1.FailedReservationOrBuilder getFailedReservationsOrBuilder(
      int index) {
    return failedReservations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    for (int i = 0; i < reservedVariantIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reservedVariantIds_.getRaw(i));
    }
    for (int i = 0; i < failedReservations_.size(); i++) {
      output.writeMessage(4, failedReservations_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < reservedVariantIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(reservedVariantIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getReservedVariantIdsList().size();
    }
    for (int i = 0; i < failedReservations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, failedReservations_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ecmsp.product.v1.ReserveProductsResponse)) {
      return super.equals(obj);
    }
    com.ecmsp.product.v1.ReserveProductsResponse other = (com.ecmsp.product.v1.ReserveProductsResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getReservedVariantIdsList()
        .equals(other.getReservedVariantIdsList())) return false;
    if (!getFailedReservationsList()
        .equals(other.getFailedReservationsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getReservedVariantIdsCount() > 0) {
      hash = (37 * hash) + RESERVED_VARIANT_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getReservedVariantIdsList().hashCode();
    }
    if (getFailedReservationsCount() > 0) {
      hash = (37 * hash) + FAILED_RESERVATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getFailedReservationsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ecmsp.product.v1.ReserveProductsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecmsp.product.v1.ReserveProductsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecmsp.product.v1.ReserveProductsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecmsp.product.v1.ReserveProductsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecmsp.product.v1.ReserveProductsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecmsp.product.v1.ReserveProductsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecmsp.product.v1.ReserveProductsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecmsp.product.v1.ReserveProductsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ecmsp.product.v1.ReserveProductsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ecmsp.product.v1.ReserveProductsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ecmsp.product.v1.ReserveProductsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecmsp.product.v1.ReserveProductsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ecmsp.product.v1.ReserveProductsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code product.v1.ReserveProductsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:product.v1.ReserveProductsResponse)
      com.ecmsp.product.v1.ReserveProductsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ecmsp.product.v1.ProductReservationServiceProto.internal_static_product_v1_ReserveProductsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ecmsp.product.v1.ProductReservationServiceProto.internal_static_product_v1_ReserveProductsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ecmsp.product.v1.ReserveProductsResponse.class, com.ecmsp.product.v1.ReserveProductsResponse.Builder.class);
    }

    // Construct using com.ecmsp.product.v1.ReserveProductsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      success_ = false;
      message_ = "";
      reservedVariantIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (failedReservationsBuilder_ == null) {
        failedReservations_ = java.util.Collections.emptyList();
      } else {
        failedReservations_ = null;
        failedReservationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ecmsp.product.v1.ProductReservationServiceProto.internal_static_product_v1_ReserveProductsResponse_descriptor;
    }

    @java.lang.Override
    public com.ecmsp.product.v1.ReserveProductsResponse getDefaultInstanceForType() {
      return com.ecmsp.product.v1.ReserveProductsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.ecmsp.product.v1.ReserveProductsResponse build() {
      com.ecmsp.product.v1.ReserveProductsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ecmsp.product.v1.ReserveProductsResponse buildPartial() {
      com.ecmsp.product.v1.ReserveProductsResponse result = new com.ecmsp.product.v1.ReserveProductsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.ecmsp.product.v1.ReserveProductsResponse result) {
      if (failedReservationsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          failedReservations_ = java.util.Collections.unmodifiableList(failedReservations_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.failedReservations_ = failedReservations_;
      } else {
        result.failedReservations_ = failedReservationsBuilder_.build();
      }
    }

    private void buildPartial0(com.ecmsp.product.v1.ReserveProductsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.success_ = success_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = message_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        reservedVariantIds_.makeImmutable();
        result.reservedVariantIds_ = reservedVariantIds_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ecmsp.product.v1.ReserveProductsResponse) {
        return mergeFrom((com.ecmsp.product.v1.ReserveProductsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ecmsp.product.v1.ReserveProductsResponse other) {
      if (other == com.ecmsp.product.v1.ReserveProductsResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.reservedVariantIds_.isEmpty()) {
        if (reservedVariantIds_.isEmpty()) {
          reservedVariantIds_ = other.reservedVariantIds_;
          bitField0_ |= 0x00000004;
        } else {
          ensureReservedVariantIdsIsMutable();
          reservedVariantIds_.addAll(other.reservedVariantIds_);
        }
        onChanged();
      }
      if (failedReservationsBuilder_ == null) {
        if (!other.failedReservations_.isEmpty()) {
          if (failedReservations_.isEmpty()) {
            failedReservations_ = other.failedReservations_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureFailedReservationsIsMutable();
            failedReservations_.addAll(other.failedReservations_);
          }
          onChanged();
        }
      } else {
        if (!other.failedReservations_.isEmpty()) {
          if (failedReservationsBuilder_.isEmpty()) {
            failedReservationsBuilder_.dispose();
            failedReservationsBuilder_ = null;
            failedReservations_ = other.failedReservations_;
            bitField0_ = (bitField0_ & ~0x00000008);
            failedReservationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFailedReservationsFieldBuilder() : null;
          } else {
            failedReservationsBuilder_.addAllMessages(other.failedReservations_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureReservedVariantIdsIsMutable();
              reservedVariantIds_.add(s);
              break;
            } // case 26
            case 34: {
              com.ecmsp.product.v1.FailedReservation m =
                  input.readMessage(
                      com.ecmsp.product.v1.FailedReservation.parser(),
                      extensionRegistry);
              if (failedReservationsBuilder_ == null) {
                ensureFailedReservationsIsMutable();
                failedReservations_.add(m);
              } else {
                failedReservationsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList reservedVariantIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureReservedVariantIdsIsMutable() {
      if (!reservedVariantIds_.isModifiable()) {
        reservedVariantIds_ = new com.google.protobuf.LazyStringArrayList(reservedVariantIds_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @return A list containing the reservedVariantIds.
     */
    public com.google.protobuf.ProtocolStringList
        getReservedVariantIdsList() {
      reservedVariantIds_.makeImmutable();
      return reservedVariantIds_;
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @return The count of reservedVariantIds.
     */
    public int getReservedVariantIdsCount() {
      return reservedVariantIds_.size();
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @param index The index of the element to return.
     * @return The reservedVariantIds at the given index.
     */
    public java.lang.String getReservedVariantIds(int index) {
      return reservedVariantIds_.get(index);
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the reservedVariantIds at the given index.
     */
    public com.google.protobuf.ByteString
        getReservedVariantIdsBytes(int index) {
      return reservedVariantIds_.getByteString(index);
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @param index The index to set the value at.
     * @param value The reservedVariantIds to set.
     * @return This builder for chaining.
     */
    public Builder setReservedVariantIds(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureReservedVariantIdsIsMutable();
      reservedVariantIds_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @param value The reservedVariantIds to add.
     * @return This builder for chaining.
     */
    public Builder addReservedVariantIds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureReservedVariantIdsIsMutable();
      reservedVariantIds_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @param values The reservedVariantIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllReservedVariantIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureReservedVariantIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, reservedVariantIds_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReservedVariantIds() {
      reservedVariantIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string reserved_variant_ids = 3;</code>
     * @param value The bytes of the reservedVariantIds to add.
     * @return This builder for chaining.
     */
    public Builder addReservedVariantIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureReservedVariantIdsIsMutable();
      reservedVariantIds_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<com.ecmsp.product.v1.FailedReservation> failedReservations_ =
      java.util.Collections.emptyList();
    private void ensureFailedReservationsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        failedReservations_ = new java.util.ArrayList<com.ecmsp.product.v1.FailedReservation>(failedReservations_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ecmsp.product.v1.FailedReservation, com.ecmsp.product.v1.FailedReservation.Builder, com.ecmsp.product.v1.FailedReservationOrBuilder> failedReservationsBuilder_;

    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public java.util.List<com.ecmsp.product.v1.FailedReservation> getFailedReservationsList() {
      if (failedReservationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(failedReservations_);
      } else {
        return failedReservationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public int getFailedReservationsCount() {
      if (failedReservationsBuilder_ == null) {
        return failedReservations_.size();
      } else {
        return failedReservationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public com.ecmsp.product.v1.FailedReservation getFailedReservations(int index) {
      if (failedReservationsBuilder_ == null) {
        return failedReservations_.get(index);
      } else {
        return failedReservationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public Builder setFailedReservations(
        int index, com.ecmsp.product.v1.FailedReservation value) {
      if (failedReservationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFailedReservationsIsMutable();
        failedReservations_.set(index, value);
        onChanged();
      } else {
        failedReservationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public Builder setFailedReservations(
        int index, com.ecmsp.product.v1.FailedReservation.Builder builderForValue) {
      if (failedReservationsBuilder_ == null) {
        ensureFailedReservationsIsMutable();
        failedReservations_.set(index, builderForValue.build());
        onChanged();
      } else {
        failedReservationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public Builder addFailedReservations(com.ecmsp.product.v1.FailedReservation value) {
      if (failedReservationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFailedReservationsIsMutable();
        failedReservations_.add(value);
        onChanged();
      } else {
        failedReservationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public Builder addFailedReservations(
        int index, com.ecmsp.product.v1.FailedReservation value) {
      if (failedReservationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFailedReservationsIsMutable();
        failedReservations_.add(index, value);
        onChanged();
      } else {
        failedReservationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public Builder addFailedReservations(
        com.ecmsp.product.v1.FailedReservation.Builder builderForValue) {
      if (failedReservationsBuilder_ == null) {
        ensureFailedReservationsIsMutable();
        failedReservations_.add(builderForValue.build());
        onChanged();
      } else {
        failedReservationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public Builder addFailedReservations(
        int index, com.ecmsp.product.v1.FailedReservation.Builder builderForValue) {
      if (failedReservationsBuilder_ == null) {
        ensureFailedReservationsIsMutable();
        failedReservations_.add(index, builderForValue.build());
        onChanged();
      } else {
        failedReservationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public Builder addAllFailedReservations(
        java.lang.Iterable<? extends com.ecmsp.product.v1.FailedReservation> values) {
      if (failedReservationsBuilder_ == null) {
        ensureFailedReservationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, failedReservations_);
        onChanged();
      } else {
        failedReservationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public Builder clearFailedReservations() {
      if (failedReservationsBuilder_ == null) {
        failedReservations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        failedReservationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public Builder removeFailedReservations(int index) {
      if (failedReservationsBuilder_ == null) {
        ensureFailedReservationsIsMutable();
        failedReservations_.remove(index);
        onChanged();
      } else {
        failedReservationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public com.ecmsp.product.v1.FailedReservation.Builder getFailedReservationsBuilder(
        int index) {
      return getFailedReservationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public com.ecmsp.product.v1.FailedReservationOrBuilder getFailedReservationsOrBuilder(
        int index) {
      if (failedReservationsBuilder_ == null) {
        return failedReservations_.get(index);  } else {
        return failedReservationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public java.util.List<? extends com.ecmsp.product.v1.FailedReservationOrBuilder> 
         getFailedReservationsOrBuilderList() {
      if (failedReservationsBuilder_ != null) {
        return failedReservationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(failedReservations_);
      }
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public com.ecmsp.product.v1.FailedReservation.Builder addFailedReservationsBuilder() {
      return getFailedReservationsFieldBuilder().addBuilder(
          com.ecmsp.product.v1.FailedReservation.getDefaultInstance());
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public com.ecmsp.product.v1.FailedReservation.Builder addFailedReservationsBuilder(
        int index) {
      return getFailedReservationsFieldBuilder().addBuilder(
          index, com.ecmsp.product.v1.FailedReservation.getDefaultInstance());
    }
    /**
     * <code>repeated .product.v1.FailedReservation failed_reservations = 4;</code>
     */
    public java.util.List<com.ecmsp.product.v1.FailedReservation.Builder> 
         getFailedReservationsBuilderList() {
      return getFailedReservationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ecmsp.product.v1.FailedReservation, com.ecmsp.product.v1.FailedReservation.Builder, com.ecmsp.product.v1.FailedReservationOrBuilder> 
        getFailedReservationsFieldBuilder() {
      if (failedReservationsBuilder_ == null) {
        failedReservationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ecmsp.product.v1.FailedReservation, com.ecmsp.product.v1.FailedReservation.Builder, com.ecmsp.product.v1.FailedReservationOrBuilder>(
                failedReservations_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        failedReservations_ = null;
      }
      return failedReservationsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:product.v1.ReserveProductsResponse)
  }

  // @@protoc_insertion_point(class_scope:product.v1.ReserveProductsResponse)
  private static final com.ecmsp.product.v1.ReserveProductsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ecmsp.product.v1.ReserveProductsResponse();
  }

  public static com.ecmsp.product.v1.ReserveProductsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReserveProductsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ReserveProductsResponse>() {
    @java.lang.Override
    public ReserveProductsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReserveProductsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReserveProductsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ecmsp.product.v1.ReserveProductsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

