// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/product.proto

package com.ecmsp.product.v1;

public interface VariantDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.v1.VariantDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string variant_id = 1;</code>
   * @return The variantId.
   */
  java.lang.String getVariantId();
  /**
   * <code>string variant_id = 1;</code>
   * @return The bytes for variantId.
   */
  com.google.protobuf.ByteString
      getVariantIdBytes();

  /**
   * <code>.google.type.Decimal price = 2;</code>
   * @return Whether the price field is set.
   */
  boolean hasPrice();
  /**
   * <code>.google.type.Decimal price = 2;</code>
   * @return The price.
   */
  com.google.type.Decimal getPrice();
  /**
   * <code>.google.type.Decimal price = 2;</code>
   */
  com.google.type.DecimalOrBuilder getPriceOrBuilder();

  /**
   * <code>int32 stock_quantity = 3;</code>
   * @return The stockQuantity.
   */
  int getStockQuantity();

  /**
   * <code>string image_url = 4;</code>
   * @return The imageUrl.
   */
  java.lang.String getImageUrl();
  /**
   * <code>string image_url = 4;</code>
   * @return The bytes for imageUrl.
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();

  /**
   * <code>string description = 5;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 5;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.google.protobuf.Struct additional_properties = 6;</code>
   * @return Whether the additionalProperties field is set.
   */
  boolean hasAdditionalProperties();
  /**
   * <code>.google.protobuf.Struct additional_properties = 6;</code>
   * @return The additionalProperties.
   */
  com.google.protobuf.Struct getAdditionalProperties();
  /**
   * <code>.google.protobuf.Struct additional_properties = 6;</code>
   */
  com.google.protobuf.StructOrBuilder getAdditionalPropertiesOrBuilder();
}
