// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/v1/variant_reservation_service.proto

package com.ecmsp.product.v1;

public final class VariantReservationServiceProto {
  private VariantReservationServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,product/v1/variant_reservation_service" +
      ".proto\022\nproduct.v1\032$product/v1/variant_r" +
      "eservation.proto2\200\003\n\031VariantReservationS" +
      "ervice\022x\n\031CreateVariantsReservation\022,.pr" +
      "oduct.v1.CreateVariantsReservationReques" +
      "t\032-.product.v1.CreateVariantsReservation" +
      "Response\022x\n\031RemoveVariantsReservation\022,." +
      "product.v1.RemoveVariantsReservationRequ" +
      "est\032-.product.v1.RemoveVariantsReservati" +
      "onResponse\022o\n\026GetVariantsReservation\022).p" +
      "roduct.v1.GetVariantsReservationRequest\032" +
      "*.product.v1.GetVariantsReservationRespo" +
      "nseB8\n\024com.ecmsp.product.v1B\036VariantRese" +
      "rvationServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ecmsp.product.v1.VariantReservationProto.getDescriptor(),
        });
    com.ecmsp.product.v1.VariantReservationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
