// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics/v1/statistics_service.proto

package com.ecmsp.statistics.v1;

public interface GetAvailableVariantsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:statistics.v1.GetAvailableVariantsRequest)
    com.google.protobuf.MessageOrBuilder {
}
