// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics/v1/regression_line.proto

package com.ecmsp.statistics.v1;

public interface LinearRegressionLineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:statistics.v1.LinearRegressionLine)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double slope = 1;</code>
   * @return The slope.
   */
  double getSlope();

  /**
   * <code>double intercept = 2;</code>
   * @return The intercept.
   */
  double getIntercept();

  /**
   * <code>string valid_from = 3;</code>
   * @return The validFrom.
   */
  java.lang.String getValidFrom();
  /**
   * <code>string valid_from = 3;</code>
   * @return The bytes for validFrom.
   */
  com.google.protobuf.ByteString
      getValidFromBytes();

  /**
   * <code>string valid_to = 4;</code>
   * @return The validTo.
   */
  java.lang.String getValidTo();
  /**
   * <code>string valid_to = 4;</code>
   * @return The bytes for validTo.
   */
  com.google.protobuf.ByteString
      getValidToBytes();

  /**
   * <code>string estimated_depletion_date = 5;</code>
   * @return The estimatedDepletionDate.
   */
  java.lang.String getEstimatedDepletionDate();
  /**
   * <code>string estimated_depletion_date = 5;</code>
   * @return The bytes for estimatedDepletionDate.
   */
  com.google.protobuf.ByteString
      getEstimatedDepletionDateBytes();

  /**
   * <code>double r_squared = 6;</code>
   * @return The rSquared.
   */
  double getRSquared();
}
