// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics/v1/variant_info.proto

package com.ecmsp.statistics.v1;

public interface VariantInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:statistics.v1.VariantInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string variant_id = 1;</code>
   * @return The variantId.
   */
  java.lang.String getVariantId();
  /**
   * <code>string variant_id = 1;</code>
   * @return The bytes for variantId.
   */
  com.google.protobuf.ByteString
      getVariantIdBytes();

  /**
   * <code>string product_id = 2;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 2;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>string product_name = 3;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 3;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>bool has_sales_data = 4;</code>
   * @return The hasSalesData.
   */
  boolean getHasSalesData();

  /**
   * <code>bool has_stock_data = 5;</code>
   * @return The hasStockData.
   */
  boolean getHasStockData();

  /**
   * <code>string last_sale_date = 6;</code>
   * @return The lastSaleDate.
   */
  java.lang.String getLastSaleDate();
  /**
   * <code>string last_sale_date = 6;</code>
   * @return The bytes for lastSaleDate.
   */
  com.google.protobuf.ByteString
      getLastSaleDateBytes();

  /**
   * <code>optional int32 current_stock = 7;</code>
   * @return Whether the currentStock field is set.
   */
  boolean hasCurrentStock();
  /**
   * <code>optional int32 current_stock = 7;</code>
   * @return The currentStock.
   */
  int getCurrentStock();
}
