// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics/v1/variant_info.proto

package com.ecmsp.statistics.v1;

/**
 * Protobuf type {@code statistics.v1.VariantInfo}
 */
public final class VariantInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:statistics.v1.VariantInfo)
    VariantInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VariantInfo.newBuilder() to construct.
  private VariantInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VariantInfo() {
    variantId_ = "";
    productId_ = "";
    productName_ = "";
    lastSaleDate_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VariantInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ecmsp.statistics.v1.VariantInfoProto.internal_static_statistics_v1_VariantInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ecmsp.statistics.v1.VariantInfoProto.internal_static_statistics_v1_VariantInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ecmsp.statistics.v1.VariantInfo.class, com.ecmsp.statistics.v1.VariantInfo.Builder.class);
  }

  private int bitField0_;
  public static final int VARIANT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object variantId_ = "";
  /**
   * <code>string variant_id = 1;</code>
   * @return The variantId.
   */
  @java.lang.Override
  public java.lang.String getVariantId() {
    java.lang.Object ref = variantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      variantId_ = s;
      return s;
    }
  }
  /**
   * <code>string variant_id = 1;</code>
   * @return The bytes for variantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVariantIdBytes() {
    java.lang.Object ref = variantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      variantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object productId_ = "";
  /**
   * <code>string product_id = 2;</code>
   * @return The productId.
   */
  @java.lang.Override
  public java.lang.String getProductId() {
    java.lang.Object ref = productId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productId_ = s;
      return s;
    }
  }
  /**
   * <code>string product_id = 2;</code>
   * @return The bytes for productId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductIdBytes() {
    java.lang.Object ref = productId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCT_NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object productName_ = "";
  /**
   * <code>string product_name = 3;</code>
   * @return The productName.
   */
  @java.lang.Override
  public java.lang.String getProductName() {
    java.lang.Object ref = productName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productName_ = s;
      return s;
    }
  }
  /**
   * <code>string product_name = 3;</code>
   * @return The bytes for productName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    java.lang.Object ref = productName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HAS_SALES_DATA_FIELD_NUMBER = 4;
  private boolean hasSalesData_ = false;
  /**
   * <code>bool has_sales_data = 4;</code>
   * @return The hasSalesData.
   */
  @java.lang.Override
  public boolean getHasSalesData() {
    return hasSalesData_;
  }

  public static final int HAS_STOCK_DATA_FIELD_NUMBER = 5;
  private boolean hasStockData_ = false;
  /**
   * <code>bool has_stock_data = 5;</code>
   * @return The hasStockData.
   */
  @java.lang.Override
  public boolean getHasStockData() {
    return hasStockData_;
  }

  public static final int LAST_SALE_DATE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lastSaleDate_ = "";
  /**
   * <code>string last_sale_date = 6;</code>
   * @return The lastSaleDate.
   */
  @java.lang.Override
  public java.lang.String getLastSaleDate() {
    java.lang.Object ref = lastSaleDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastSaleDate_ = s;
      return s;
    }
  }
  /**
   * <code>string last_sale_date = 6;</code>
   * @return The bytes for lastSaleDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastSaleDateBytes() {
    java.lang.Object ref = lastSaleDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastSaleDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENT_STOCK_FIELD_NUMBER = 7;
  private int currentStock_ = 0;
  /**
   * <code>optional int32 current_stock = 7;</code>
   * @return Whether the currentStock field is set.
   */
  @java.lang.Override
  public boolean hasCurrentStock() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 current_stock = 7;</code>
   * @return The currentStock.
   */
  @java.lang.Override
  public int getCurrentStock() {
    return currentStock_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(variantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, variantId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, productName_);
    }
    if (hasSalesData_ != false) {
      output.writeBool(4, hasSalesData_);
    }
    if (hasStockData_ != false) {
      output.writeBool(5, hasStockData_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastSaleDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, lastSaleDate_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(7, currentStock_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(variantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, variantId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, productName_);
    }
    if (hasSalesData_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, hasSalesData_);
    }
    if (hasStockData_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, hasStockData_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastSaleDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, lastSaleDate_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, currentStock_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ecmsp.statistics.v1.VariantInfo)) {
      return super.equals(obj);
    }
    com.ecmsp.statistics.v1.VariantInfo other = (com.ecmsp.statistics.v1.VariantInfo) obj;

    if (!getVariantId()
        .equals(other.getVariantId())) return false;
    if (!getProductId()
        .equals(other.getProductId())) return false;
    if (!getProductName()
        .equals(other.getProductName())) return false;
    if (getHasSalesData()
        != other.getHasSalesData()) return false;
    if (getHasStockData()
        != other.getHasStockData()) return false;
    if (!getLastSaleDate()
        .equals(other.getLastSaleDate())) return false;
    if (hasCurrentStock() != other.hasCurrentStock()) return false;
    if (hasCurrentStock()) {
      if (getCurrentStock()
          != other.getCurrentStock()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VARIANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getVariantId().hashCode();
    hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProductId().hashCode();
    hash = (37 * hash) + PRODUCT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getProductName().hashCode();
    hash = (37 * hash) + HAS_SALES_DATA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasSalesData());
    hash = (37 * hash) + HAS_STOCK_DATA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasStockData());
    hash = (37 * hash) + LAST_SALE_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getLastSaleDate().hashCode();
    if (hasCurrentStock()) {
      hash = (37 * hash) + CURRENT_STOCK_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentStock();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ecmsp.statistics.v1.VariantInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecmsp.statistics.v1.VariantInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecmsp.statistics.v1.VariantInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecmsp.statistics.v1.VariantInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecmsp.statistics.v1.VariantInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecmsp.statistics.v1.VariantInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecmsp.statistics.v1.VariantInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecmsp.statistics.v1.VariantInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ecmsp.statistics.v1.VariantInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ecmsp.statistics.v1.VariantInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ecmsp.statistics.v1.VariantInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecmsp.statistics.v1.VariantInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ecmsp.statistics.v1.VariantInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code statistics.v1.VariantInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:statistics.v1.VariantInfo)
      com.ecmsp.statistics.v1.VariantInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ecmsp.statistics.v1.VariantInfoProto.internal_static_statistics_v1_VariantInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ecmsp.statistics.v1.VariantInfoProto.internal_static_statistics_v1_VariantInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ecmsp.statistics.v1.VariantInfo.class, com.ecmsp.statistics.v1.VariantInfo.Builder.class);
    }

    // Construct using com.ecmsp.statistics.v1.VariantInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      variantId_ = "";
      productId_ = "";
      productName_ = "";
      hasSalesData_ = false;
      hasStockData_ = false;
      lastSaleDate_ = "";
      currentStock_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ecmsp.statistics.v1.VariantInfoProto.internal_static_statistics_v1_VariantInfo_descriptor;
    }

    @java.lang.Override
    public com.ecmsp.statistics.v1.VariantInfo getDefaultInstanceForType() {
      return com.ecmsp.statistics.v1.VariantInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.ecmsp.statistics.v1.VariantInfo build() {
      com.ecmsp.statistics.v1.VariantInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ecmsp.statistics.v1.VariantInfo buildPartial() {
      com.ecmsp.statistics.v1.VariantInfo result = new com.ecmsp.statistics.v1.VariantInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ecmsp.statistics.v1.VariantInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.variantId_ = variantId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.productId_ = productId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.productName_ = productName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.hasSalesData_ = hasSalesData_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.hasStockData_ = hasStockData_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.lastSaleDate_ = lastSaleDate_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.currentStock_ = currentStock_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ecmsp.statistics.v1.VariantInfo) {
        return mergeFrom((com.ecmsp.statistics.v1.VariantInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ecmsp.statistics.v1.VariantInfo other) {
      if (other == com.ecmsp.statistics.v1.VariantInfo.getDefaultInstance()) return this;
      if (!other.getVariantId().isEmpty()) {
        variantId_ = other.variantId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getProductId().isEmpty()) {
        productId_ = other.productId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getProductName().isEmpty()) {
        productName_ = other.productName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getHasSalesData() != false) {
        setHasSalesData(other.getHasSalesData());
      }
      if (other.getHasStockData() != false) {
        setHasStockData(other.getHasStockData());
      }
      if (!other.getLastSaleDate().isEmpty()) {
        lastSaleDate_ = other.lastSaleDate_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasCurrentStock()) {
        setCurrentStock(other.getCurrentStock());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              variantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              productId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              productName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              hasSalesData_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              hasStockData_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              lastSaleDate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              currentStock_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object variantId_ = "";
    /**
     * <code>string variant_id = 1;</code>
     * @return The variantId.
     */
    public java.lang.String getVariantId() {
      java.lang.Object ref = variantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        variantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string variant_id = 1;</code>
     * @return The bytes for variantId.
     */
    public com.google.protobuf.ByteString
        getVariantIdBytes() {
      java.lang.Object ref = variantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        variantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string variant_id = 1;</code>
     * @param value The variantId to set.
     * @return This builder for chaining.
     */
    public Builder setVariantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      variantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string variant_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVariantId() {
      variantId_ = getDefaultInstance().getVariantId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string variant_id = 1;</code>
     * @param value The bytes for variantId to set.
     * @return This builder for chaining.
     */
    public Builder setVariantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      variantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object productId_ = "";
    /**
     * <code>string product_id = 2;</code>
     * @return The productId.
     */
    public java.lang.String getProductId() {
      java.lang.Object ref = productId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string product_id = 2;</code>
     * @return The bytes for productId.
     */
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      java.lang.Object ref = productId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string product_id = 2;</code>
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      productId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string product_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      productId_ = getDefaultInstance().getProductId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string product_id = 2;</code>
     * @param value The bytes for productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      productId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object productName_ = "";
    /**
     * <code>string product_name = 3;</code>
     * @return The productName.
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string product_name = 3;</code>
     * @return The bytes for productName.
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string product_name = 3;</code>
     * @param value The productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      productName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string product_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductName() {
      productName_ = getDefaultInstance().getProductName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string product_name = 3;</code>
     * @param value The bytes for productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      productName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private boolean hasSalesData_ ;
    /**
     * <code>bool has_sales_data = 4;</code>
     * @return The hasSalesData.
     */
    @java.lang.Override
    public boolean getHasSalesData() {
      return hasSalesData_;
    }
    /**
     * <code>bool has_sales_data = 4;</code>
     * @param value The hasSalesData to set.
     * @return This builder for chaining.
     */
    public Builder setHasSalesData(boolean value) {

      hasSalesData_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool has_sales_data = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasSalesData() {
      bitField0_ = (bitField0_ & ~0x00000008);
      hasSalesData_ = false;
      onChanged();
      return this;
    }

    private boolean hasStockData_ ;
    /**
     * <code>bool has_stock_data = 5;</code>
     * @return The hasStockData.
     */
    @java.lang.Override
    public boolean getHasStockData() {
      return hasStockData_;
    }
    /**
     * <code>bool has_stock_data = 5;</code>
     * @param value The hasStockData to set.
     * @return This builder for chaining.
     */
    public Builder setHasStockData(boolean value) {

      hasStockData_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool has_stock_data = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasStockData() {
      bitField0_ = (bitField0_ & ~0x00000010);
      hasStockData_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object lastSaleDate_ = "";
    /**
     * <code>string last_sale_date = 6;</code>
     * @return The lastSaleDate.
     */
    public java.lang.String getLastSaleDate() {
      java.lang.Object ref = lastSaleDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastSaleDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string last_sale_date = 6;</code>
     * @return The bytes for lastSaleDate.
     */
    public com.google.protobuf.ByteString
        getLastSaleDateBytes() {
      java.lang.Object ref = lastSaleDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastSaleDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string last_sale_date = 6;</code>
     * @param value The lastSaleDate to set.
     * @return This builder for chaining.
     */
    public Builder setLastSaleDate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lastSaleDate_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string last_sale_date = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastSaleDate() {
      lastSaleDate_ = getDefaultInstance().getLastSaleDate();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string last_sale_date = 6;</code>
     * @param value The bytes for lastSaleDate to set.
     * @return This builder for chaining.
     */
    public Builder setLastSaleDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lastSaleDate_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private int currentStock_ ;
    /**
     * <code>optional int32 current_stock = 7;</code>
     * @return Whether the currentStock field is set.
     */
    @java.lang.Override
    public boolean hasCurrentStock() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int32 current_stock = 7;</code>
     * @return The currentStock.
     */
    @java.lang.Override
    public int getCurrentStock() {
      return currentStock_;
    }
    /**
     * <code>optional int32 current_stock = 7;</code>
     * @param value The currentStock to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentStock(int value) {

      currentStock_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 current_stock = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentStock() {
      bitField0_ = (bitField0_ & ~0x00000040);
      currentStock_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:statistics.v1.VariantInfo)
  }

  // @@protoc_insertion_point(class_scope:statistics.v1.VariantInfo)
  private static final com.ecmsp.statistics.v1.VariantInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ecmsp.statistics.v1.VariantInfo();
  }

  public static com.ecmsp.statistics.v1.VariantInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VariantInfo>
      PARSER = new com.google.protobuf.AbstractParser<VariantInfo>() {
    @java.lang.Override
    public VariantInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VariantInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VariantInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ecmsp.statistics.v1.VariantInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

