// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/v1/order.proto

package com.ecmsp.order.v1;

public interface CreateOrderItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.v1.CreateOrderItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string variant_id = 1;</code>
   * @return The variantId.
   */
  java.lang.String getVariantId();
  /**
   * <code>string variant_id = 1;</code>
   * @return The bytes for variantId.
   */
  com.google.protobuf.ByteString
      getVariantIdBytes();

  /**
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  int getQuantity();
}
