// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/v1/return_service.proto

package com.ecmsp.order.v1;

public interface ListReturnsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.v1.ListReturnsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .order.v1.GetReturnResponse returns = 1;</code>
   */
  java.util.List<com.ecmsp.order.v1.GetReturnResponse> 
      getReturnsList();
  /**
   * <code>repeated .order.v1.GetReturnResponse returns = 1;</code>
   */
  com.ecmsp.order.v1.GetReturnResponse getReturns(int index);
  /**
   * <code>repeated .order.v1.GetReturnResponse returns = 1;</code>
   */
  int getReturnsCount();
  /**
   * <code>repeated .order.v1.GetReturnResponse returns = 1;</code>
   */
  java.util.List<? extends com.ecmsp.order.v1.GetReturnResponseOrBuilder> 
      getReturnsOrBuilderList();
  /**
   * <code>repeated .order.v1.GetReturnResponse returns = 1;</code>
   */
  com.ecmsp.order.v1.GetReturnResponseOrBuilder getReturnsOrBuilder(
      int index);
}
