// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/v1/order_status.proto

package com.ecmsp.order.v1;

public final class OrderStatusProto {
  private OrderStatusProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033order/v1/order_status.proto\022\010order.v1*" +
      "\220\002\n\013OrderStatus\022\034\n\030ORDER_STATUS_UNSPECIF" +
      "IED\020\000\022\030\n\024ORDER_STATUS_PENDING\020\001\022\033\n\027ORDER" +
      "_STATUS_PROCESSING\020\002\022\025\n\021ORDER_STATUS_PAI" +
      "D\020\003\022\027\n\023ORDER_STATUS_FAILED\020\004\022\032\n\026ORDER_ST" +
      "ATUS_CANCELLED\020\005\022!\n\035ORDER_STATUS_RETURN_" +
      "REQUESTED\020\006\022\"\n\036ORDER_STATUS_RETURN_PROCE" +
      "SSING\020\007\022\031\n\025ORDER_STATUS_RETURNED\020\010B(\n\022co" +
      "m.ecmsp.order.v1B\020OrderStatusProtoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
