// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/v1/order.proto

package com.ecmsp.order.v1;

public final class OrderProto {
  private OrderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_OrderItemDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_OrderItemDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024order/v1/order.proto\022\010order.v1\032\033order/" +
      "v1/order_status.proto\"\245\001\n\020OrderItemDetai" +
      "ls\022\017\n\007item_id\030\001 \001(\t\022\022\n\nvariant_id\030\002 \001(\t\022" +
      "\014\n\004name\030\003 \001(\t\022\020\n\010quantity\030\004 \001(\005\022\r\n\005price" +
      "\030\005 \001(\001\022\021\n\timage_url\030\006 \001(\t\022\023\n\013description" +
      "\030\007 \001(\t\022\025\n\ris_returnable\030\010 \001(\010\"\252\001\n\005Order\022" +
      "\020\n\010order_id\030\001 \001(\t\022\026\n\016reservation_id\030\002 \001(" +
      "\t\022+\n\014order_status\030\003 \001(\0162\025.order.v1.Order" +
      "Status\022\014\n\004date\030\004 \001(\t\022)\n\005items\030\005 \003(\0132\032.or" +
      "der.v1.OrderItemDetails\022\021\n\tclient_id\030\006 \001" +
      "(\tB\"\n\022com.ecmsp.order.v1B\nOrderProtoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ecmsp.order.v1.OrderStatusProto.getDescriptor(),
        });
    internal_static_order_v1_OrderItemDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_order_v1_OrderItemDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_OrderItemDetails_descriptor,
        new java.lang.String[] { "ItemId", "VariantId", "Name", "Quantity", "Price", "ImageUrl", "Description", "IsReturnable", });
    internal_static_order_v1_Order_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_order_v1_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_Order_descriptor,
        new java.lang.String[] { "OrderId", "ReservationId", "OrderStatus", "Date", "Items", "ClientId", });
    com.ecmsp.order.v1.OrderStatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
