// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/v1/order_service.proto

package com.ecmsp.order.v1;

public final class OrderServiceProto {
  private OrderServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_GetOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_GetOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_GetOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_GetOrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_GetOrderStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_GetOrderStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_GetOrderStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_GetOrderStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_GetOrderItemsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_GetOrderItemsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_GetOrderItemsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_GetOrderItemsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_ListOrdersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_ListOrdersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_ListOrdersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_ListOrdersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_ListOrdersByUserIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_ListOrdersByUserIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_ListOrdersByUserIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_ListOrdersByUserIdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034order/v1/order_service.proto\022\010order.v1" +
      "\032\033order/v1/order_status.proto\032\024order/v1/" +
      "order.proto\"#\n\017GetOrderRequest\022\020\n\010order_" +
      "id\030\001 \001(\t\"\212\001\n\020GetOrderResponse\022\020\n\010order_i" +
      "d\030\001 \001(\t\022+\n\014order_status\030\003 \001(\0162\025.order.v1" +
      ".OrderStatus\022\014\n\004date\030\004 \001(\t\022)\n\005items\030\005 \003(" +
      "\0132\032.order.v1.OrderItemDetails\")\n\025GetOrde" +
      "rStatusRequest\022\020\n\010order_id\030\001 \001(\t\"W\n\026GetO" +
      "rderStatusResponse\022\020\n\010order_id\030\001 \001(\t\022+\n\014" +
      "order_status\030\002 \001(\0162\025.order.v1.OrderStatu" +
      "s\"(\n\024GetOrderItemsRequest\022\020\n\010order_id\030\001 " +
      "\001(\t\"B\n\025GetOrderItemsResponse\022)\n\005items\030\001 " +
      "\003(\0132\032.order.v1.OrderItemDetails\"\023\n\021ListO" +
      "rdersRequest\"@\n\022ListOrdersResponse\022*\n\006or" +
      "ders\030\001 \003(\0132\032.order.v1.GetOrderResponse\"\033" +
      "\n\031ListOrdersByUserIdRequest\"H\n\032ListOrder" +
      "sByUserIdResponse\022*\n\006orders\030\001 \003(\0132\032.orde" +
      "r.v1.GetOrderResponse2\242\003\n\014OrderService\022A" +
      "\n\010GetOrder\022\031.order.v1.GetOrderRequest\032\032." +
      "order.v1.GetOrderResponse\022S\n\016GetOrderSta" +
      "tus\022\037.order.v1.GetOrderStatusRequest\032 .o" +
      "rder.v1.GetOrderStatusResponse\022P\n\rGetOrd" +
      "erItems\022\036.order.v1.GetOrderItemsRequest\032" +
      "\037.order.v1.GetOrderItemsResponse\022G\n\nList" +
      "Orders\022\033.order.v1.ListOrdersRequest\032\034.or" +
      "der.v1.ListOrdersResponse\022_\n\022ListOrdersB" +
      "yUserId\022#.order.v1.ListOrdersByUserIdReq" +
      "uest\032$.order.v1.ListOrdersByUserIdRespon" +
      "seB)\n\022com.ecmsp.order.v1B\021OrderServicePr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ecmsp.order.v1.OrderStatusProto.getDescriptor(),
          com.ecmsp.order.v1.OrderProto.getDescriptor(),
        });
    internal_static_order_v1_GetOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_order_v1_GetOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_GetOrderRequest_descriptor,
        new java.lang.String[] { "OrderId", });
    internal_static_order_v1_GetOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_order_v1_GetOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_GetOrderResponse_descriptor,
        new java.lang.String[] { "OrderId", "OrderStatus", "Date", "Items", });
    internal_static_order_v1_GetOrderStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_order_v1_GetOrderStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_GetOrderStatusRequest_descriptor,
        new java.lang.String[] { "OrderId", });
    internal_static_order_v1_GetOrderStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_order_v1_GetOrderStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_GetOrderStatusResponse_descriptor,
        new java.lang.String[] { "OrderId", "OrderStatus", });
    internal_static_order_v1_GetOrderItemsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_order_v1_GetOrderItemsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_GetOrderItemsRequest_descriptor,
        new java.lang.String[] { "OrderId", });
    internal_static_order_v1_GetOrderItemsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_order_v1_GetOrderItemsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_GetOrderItemsResponse_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_order_v1_ListOrdersRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_order_v1_ListOrdersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_ListOrdersRequest_descriptor,
        new java.lang.String[] { });
    internal_static_order_v1_ListOrdersResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_order_v1_ListOrdersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_ListOrdersResponse_descriptor,
        new java.lang.String[] { "Orders", });
    internal_static_order_v1_ListOrdersByUserIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_order_v1_ListOrdersByUserIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_ListOrdersByUserIdRequest_descriptor,
        new java.lang.String[] { });
    internal_static_order_v1_ListOrdersByUserIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_order_v1_ListOrdersByUserIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_ListOrdersByUserIdResponse_descriptor,
        new java.lang.String[] { "Orders", });
    com.ecmsp.order.v1.OrderStatusProto.getDescriptor();
    com.ecmsp.order.v1.OrderProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
