// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/v1/return_service.proto

package com.ecmsp.order.v1;

public final class ReturnServiceProto {
  private ReturnServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_CreateReturnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_CreateReturnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_CreateReturnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_CreateReturnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_GetReturnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_GetReturnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_GetReturnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_GetReturnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_ListReturnsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_ListReturnsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_ListReturnsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_ListReturnsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_ListReturnsByUserIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_ListReturnsByUserIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_v1_ListReturnsByUserIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_v1_ListReturnsByUserIdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035order/v1/return_service.proto\022\010order.v" +
      "1\"I\n\023CreateReturnRequest\022\020\n\010order_id\030\001 \001" +
      "(\t\022\020\n\010item_ids\030\002 \003(\t\022\016\n\006reason\030\003 \001(\t\"9\n\024" +
      "CreateReturnResponse\022\021\n\treturn_id\030\001 \001(\t\022" +
      "\016\n\006status\030\002 \001(\t\"%\n\020GetReturnRequest\022\021\n\tr" +
      "eturn_id\030\001 \001(\t\"n\n\021GetReturnResponse\022\021\n\tr" +
      "eturn_id\030\001 \001(\t\022\020\n\010order_id\030\002 \001(\t\022\020\n\010item" +
      "_ids\030\003 \003(\t\022\016\n\006status\030\004 \001(\t\022\022\n\ncreated_at" +
      "\030\005 \001(\t\"\024\n\022ListReturnsRequest\"C\n\023ListRetu" +
      "rnsResponse\022,\n\007returns\030\001 \003(\0132\033.order.v1." +
      "GetReturnResponse\"\034\n\032ListReturnsByUserId" +
      "Request\"K\n\033ListReturnsByUserIdResponse\022," +
      "\n\007returns\030\001 \003(\0132\033.order.v1.GetReturnResp" +
      "onse2\324\002\n\rReturnService\022M\n\014CreateReturn\022\035" +
      ".order.v1.CreateReturnRequest\032\036.order.v1" +
      ".CreateReturnResponse\022D\n\tGetReturn\022\032.ord" +
      "er.v1.GetReturnRequest\032\033.order.v1.GetRet" +
      "urnResponse\022b\n\023ListReturnsByUserId\022$.ord" +
      "er.v1.ListReturnsByUserIdRequest\032%.order" +
      ".v1.ListReturnsByUserIdResponse\022J\n\013ListR" +
      "eturns\022\034.order.v1.ListReturnsRequest\032\035.o" +
      "rder.v1.ListReturnsResponseB*\n\022com.ecmsp" +
      ".order.v1B\022ReturnServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_order_v1_CreateReturnRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_order_v1_CreateReturnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_CreateReturnRequest_descriptor,
        new java.lang.String[] { "OrderId", "ItemIds", "Reason", });
    internal_static_order_v1_CreateReturnResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_order_v1_CreateReturnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_CreateReturnResponse_descriptor,
        new java.lang.String[] { "ReturnId", "Status", });
    internal_static_order_v1_GetReturnRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_order_v1_GetReturnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_GetReturnRequest_descriptor,
        new java.lang.String[] { "ReturnId", });
    internal_static_order_v1_GetReturnResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_order_v1_GetReturnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_GetReturnResponse_descriptor,
        new java.lang.String[] { "ReturnId", "OrderId", "ItemIds", "Status", "CreatedAt", });
    internal_static_order_v1_ListReturnsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_order_v1_ListReturnsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_ListReturnsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_order_v1_ListReturnsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_order_v1_ListReturnsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_ListReturnsResponse_descriptor,
        new java.lang.String[] { "Returns", });
    internal_static_order_v1_ListReturnsByUserIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_order_v1_ListReturnsByUserIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_ListReturnsByUserIdRequest_descriptor,
        new java.lang.String[] { });
    internal_static_order_v1_ListReturnsByUserIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_order_v1_ListReturnsByUserIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_v1_ListReturnsByUserIdResponse_descriptor,
        new java.lang.String[] { "Returns", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
