// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/v1/order_service.proto

package com.ecmsp.order.v1;

public interface UpdateOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.v1.UpdateOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order_id = 1;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 1;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();
}
