// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/v1/order_service.proto

package com.ecmsp.order.v1;

public interface UpdateOrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.v1.UpdateOrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order_id = 1;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 1;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>string client_id = 2;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string client_id = 2;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>.order.v1.OrderStatus order_status = 3;</code>
   * @return The enum numeric value on the wire for orderStatus.
   */
  int getOrderStatusValue();
  /**
   * <code>.order.v1.OrderStatus order_status = 3;</code>
   * @return The orderStatus.
   */
  com.ecmsp.order.v1.OrderStatus getOrderStatus();

  /**
   * <code>string date = 4;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 4;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <pre>
   *  maybe add total price field here
   * </pre>
   *
   * <code>repeated .order.v1.OrderItemDetails items = 5;</code>
   */
  java.util.List<com.ecmsp.order.v1.OrderItemDetails> 
      getItemsList();
  /**
   * <pre>
   *  maybe add total price field here
   * </pre>
   *
   * <code>repeated .order.v1.OrderItemDetails items = 5;</code>
   */
  com.ecmsp.order.v1.OrderItemDetails getItems(int index);
  /**
   * <pre>
   *  maybe add total price field here
   * </pre>
   *
   * <code>repeated .order.v1.OrderItemDetails items = 5;</code>
   */
  int getItemsCount();
  /**
   * <pre>
   *  maybe add total price field here
   * </pre>
   *
   * <code>repeated .order.v1.OrderItemDetails items = 5;</code>
   */
  java.util.List<? extends com.ecmsp.order.v1.OrderItemDetailsOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <pre>
   *  maybe add total price field here
   * </pre>
   *
   * <code>repeated .order.v1.OrderItemDetails items = 5;</code>
   */
  com.ecmsp.order.v1.OrderItemDetailsOrBuilder getItemsOrBuilder(
      int index);
}
